a, b, c = input().split()
a = float(a)
b = float(b)
c = float(c)
pi = float(3.14159)
tr = float(((a * c) / 2))
circ = float(pi * (pow(c, 2)))
trap = float((((a + b) * c) / 2))
quad = float(pow(b, 2))
ret = float((a * b))
print(f'TRIANGULO: {tr:.3f}')
print(f'CIRCULO: {circ:.3f}')
print(f'TRAPEZIO: {trap:.3f}')
print(f'QUADRADO: {quad:.3f}')
print(f'RETANGULO: {ret:.3f}')