cod1, quant1, pc1 = input().split()
cod1 = int(cod1)
quant1 = int(quant1)
pc1 = round(float(pc1), 2)
cod2, quant2, pc2 = input().split()
cod2 = int(cod2)
quant2 = int(quant2)
pc2 = round(float(pc2), 2)
print(f'VALOR A PAGAR: R$ {((quant2 * pc2) + (quant1 * pc1)):.2f}')
